server:
  port: 9096
  servlet:
    context-path: /course-service

spring:
  application:
    name: course-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:course_db}?sslMode=REQUIRED&serverTimezone=Asia/Colombo&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Pr@d!@1227}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

internal:
  api:
    key: ${INTERNAL_API_KEY:change-me}

  student:
    base-url: ${STUDENT_URL:http://localhost:9095/students-service}

#server:
#  port: 8086
#
#spring:
#  application:
#    name: course-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/course_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: course_user
#    password: CoursePass123!
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#
#internal:
#  api:
#    key: ${INTERNAL_API_KEY:change-me}
#  student:
#    base-url: ${STUDENT_URL:http://localhost:8081}

