CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS student_db;
CREATE DATABASE IF NOT EXISTS course_db;
CREATE DATABASE IF NOT EXISTS library_db;
CREATE DATABASE IF NOT EXISTS finedb;
